# Each step is the build/test process
# the name of each step is the build context, and will get its own status updates
steps:
  - name: Look Around
    plugin: 'Shell'  # this is the default plugin
    command: "ls $SRC_DIR"  
  - name: Create Site
    command: "touch konecne.txt"
